set encoding=utf-8
syntax on
set number relativenumber
set laststatus=2
set nobackup
set nowritebackup
filetype plugin indent on
set clipboard=unnamed
set hlsearch

highlight Normal ctermbg=None
highlight LineNr ctermfg=DarkGrey

"plugins
call plug#begin()
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

" Turn off highlighting after search [https://stackoverflow.com/questions/4372660/get-rid-of-vims-highlight-after-searching-text]
nnoremap <esc> :noh<return><esc>

" Movement between panes
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" fix tabs
set tabstop=4
set shiftwidth=4
set expandtab  

" set leader key
let mapleader = " "

" quit completely
nmap <leader>qq :x<CR>

" pane commands
nmap <leader>w\ :vsp<CR>
nmap <leader>w- :sp<CR>
nmap <leader>wd :q<CR>
nmap <leader>wo :only<CR>

" buffer commands
nmap <leader>bd :q<CR>

" tab commands
nmap <leader><Tab>n :tabnew<CR>
nmap <leader><Tab>l :tabnext<CR>
nmap <leader><Tab>h :tabprev<CR>
nmap <leader><Tab>s :tab sb<CR>

nmap <leader><Tab>d :tabclose<CR>
nmap <leader><Tab>o :tabonly<CR>

" fzf stuff
nmap <leader>ff :Files<CR>
nmap <C-s> :Buffers<CR>
nmap <leader><space> :Rg<CR>
