local M = {}

function M.new()
	return {
		job = nil,
		stdout_pending = "",
		stderr_pending = "",
		next_id = 0,
		callbacks = {},
		transcript_buf = nil,
		input_buf = nil,
		transcript_win = nil,
		input_win = nil,
		help_buf = nil,
		help_win = nil,
		defer_buf = nil,
		defer_win = nil,
		tree_buf = nil,
		tree_win = nil,
		tree_preview_buf = nil,
		tree_preview_win = nil,
		tree_nodes_by_line = {},
		tree_sender_highlights_by_line = {},
		tree_leaf_id = nil,
		tree_filter_mode = "default",
		is_streaming = false,
		is_retrying = false,
		pending_retry_error = nil,
		access_mode = "readonly",
		pending_access_mode = nil,
		current_message_started = false,
		current_thinking_rendered = false,
		session_file = nil,
		pending_session_file = nil,
		session_name = nil,
		message_count = 0,
		provider = nil,
		model_id = nil,
		thinking_level = nil,
		last_updated = nil,
		transcript_refresh_scheduled = false,
		pending_user_message = nil,
		placeholder_timer = nil,
		placeholder_start_line = nil,
		placeholder_line = nil,
		placeholder_tick = 1,
		abort_requested = false,
		error_rendered_for_active_run = false,
		last_stderr_lines = {},
		transcript_items = {},
		tool_outputs = {},
		next_tool_output_id = 0,
		tool_calls = {},
		live_tool_output_by_call = {},
		live_tool_lines = {},
		thinking_outputs = {},
		next_thinking_output_id = 0,
		skill_tool_calls = {},
		skill_outputs = {},
		next_skill_output_id = 0,
		active_thinking_output_id = nil,
		active_thinking_line = nil,
		pending_transcript_item_separator = false,
		session_stats = nil,
		todo_status = nil,
		notification_status = nil,
	}
end

return M
