-- I feel like this is not needed anymore.
return {
  -- "stevearc/conform.nvim",
  -- lazy = true,
  -- event = { "BufWritePre" },
  -- cmd = { "ConformInfo" },
  -- keys = {
  --   {
  --     "<leader>cf",
  --     function()
  --       vim.lsp.buf.format()
  --     end,
  --     mode = { "n", "v" },
  --     desc = "Format Buffer",
  --   },
  -- },
  -- init = function()
  --   -- If you want the formatexpr, here is the place to set it
  --   vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"
  -- end,
  -- opts = {
  --   formatters_by_ft = {
  --     python = { "black" },
  --     sh = { "shfmt" },
  --     tex = { "latexindent" },
  --     html = { "prettier" },
  --     css = { "prettier" },
  --     javascript = { "prettier" },
  --     javascriptreact = { "prettier" },
  --     typescript = { "prettier" },
  --     typescriptreact = { "prettier" },
  --     json = { "prettier" },
  --     jsonc = { "prettier" },
  --     yaml = { "prettier" },
  --     markdown = { "prettier" },
  --     ledger = { "ledger_formatter" },
  --     lua = { "stylua" },
  --     markdown = { "prettier", "markdownlint-cli2", "markdown-toc" },
  --     ["markdown.mdx"] = { "prettier", "markdownlint-cli2", "markdown-toc" },
  --   },
  --   formatters = {
  --     ledger_formatter = {
  --       command = "ledger_formatter",
  --     },
  --     ["markdown-toc"] = {
  --       condition = function(_, ctx)
  --         for _, line in ipairs(vim.api.nvim_buf_get_lines(ctx.buf, 0, -1, false)) do
  --           if line:find("<!%-%- toc %-%->") then
  --             return true
  --           end
  --         end
  --       end,
  --     },
  --     ["markdownlint-cli2"] = {
  --       condition = function(_, ctx)
  --         local diag = vim.tbl_filter(function(d)
  --           return d.source == "markdownlint"
  --         end, vim.diagnostic.get(ctx.buf))
  --         return #diag > 0
  --       end,
  --     },
  --   },
  -- },
}
